/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ServicoController;
import Implementations.HashtableServicoRepository;
import Model.Tarefas;
import Service.ClienteServico;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guerra
 */
public class cadastroColabServico extends javax.swing.JFrame {

    private final ServicoController servicoController;

    /**
     * Creates new form cadastroColaborador
     */
    public cadastroColabServico() {
        initComponents();
        servicoController = new ServicoController(new ClienteServico(new HashtableServicoRepository()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCadastro = new javax.swing.JTabbedPane();
        tabledServico = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cadastroServico = new javax.swing.JTable();
        LabelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        LabelPreço = new javax.swing.JLabel();
        textPreco = new javax.swing.JTextField();
        buttonAdicionarServico = new javax.swing.JButton();
        buttonRemoverServico = new javax.swing.JButton();
        tabledColaborador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço"
            }
        ));
        cadastroServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroServicoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cadastroServico);

        LabelNome.setText("Nome");

        LabelPreço.setText("Preço");

        textPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecoActionPerformed(evt);
            }
        });

        buttonAdicionarServico.setText("Adicionar");
        buttonAdicionarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarServicoActionPerformed(evt);
            }
        });

        buttonRemoverServico.setText("Remover");
        buttonRemoverServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabledServicoLayout = new javax.swing.GroupLayout(tabledServico);
        tabledServico.setLayout(tabledServicoLayout);
        tabledServicoLayout.setHorizontalGroup(
            tabledServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
            .addGroup(tabledServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabledServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelNome)
                    .addComponent(textNome)
                    .addComponent(LabelPreço)
                    .addComponent(textPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addComponent(buttonAdicionarServico)
                .addGap(26, 26, 26)
                .addComponent(buttonRemoverServico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabledServicoLayout.setVerticalGroup(
            tabledServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabledServicoLayout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addComponent(LabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelPreço)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabledServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdicionarServico)
                    .addComponent(buttonRemoverServico))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tableCadastro.addTab("Serviço", tabledServico);

        javax.swing.GroupLayout tabledColaboradorLayout = new javax.swing.GroupLayout(tabledColaborador);
        tabledColaborador.setLayout(tabledColaboradorLayout);
        tabledColaboradorLayout.setHorizontalGroup(
            tabledColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
        );
        tabledColaboradorLayout.setVerticalGroup(
            tabledColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        tableCadastro.addTab("Colaborador", tabledColaborador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableCadastro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableCadastro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrecoActionPerformed

    private void buttonAdicionarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarServicoActionPerformed
        String nome = textNome.getText().trim().toLowerCase();
        String preco = textPreco.getText().trim();

        double precoDouble = 0.0;

        try {
            precoDouble = Double.parseDouble(preco);
        } catch (NumberFormatException e) {
            System.out.println("Valor de preço inválido: " + preco);
        }

        Tarefas servico = new Tarefas();
        servico.setNome(nome);
        servico.setPreco(precoDouble);
        DefaultTableModel model = (DefaultTableModel) cadastroServico.getModel();
        servicoController.adicionarServico(servico, model);
        servicoController.listarTodosServico();

        textNome.setText("");
        textPreco.setText("");


    }//GEN-LAST:event_buttonAdicionarServicoActionPerformed

    private void buttonRemoverServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverServicoActionPerformed
        int i = cadastroServico.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) cadastroServico.getModel();
        if (i >= 0) {

            String nome = (String) model.getValueAt(i, 0);
            boolean removido = servicoController.removerServico(nome);
            if (removido) {
                model.removeRow(i);
                JOptionPane.showMessageDialog(rootPane, "Serviço removido com sucesso!");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao remover o serviço da estrutura de dados.");

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um serviço antes de remover.");

        }

    }//GEN-LAST:event_buttonRemoverServicoActionPerformed

    private void cadastroServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroServicoMouseClicked
        int i = cadastroServico.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) cadastroServico.getModel();

        if (i >= 0) {
            textNome.setText((String) model.getValueAt(i, 0));

            Object precoObj = model.getValueAt(i, 1);
            if (precoObj instanceof Double) {
                Double preco = (Double) precoObj;
                textPreco.setText(String.valueOf(preco));
            } else if (precoObj instanceof String) {
                textPreco.setText((String) precoObj);
            } else {
                textPreco.setText("Valor inválido");
            }

            try {
                Double preco = Double.parseDouble(textPreco.getText());
            } catch (NumberFormatException e) {
                System.out.println("Valor de preço inválido");
            }
        }
    }//GEN-LAST:event_cadastroServicoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroColabServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroColabServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroColabServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroColabServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroColabServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelPreço;
    private javax.swing.JButton buttonAdicionarServico;
    private javax.swing.JButton buttonRemoverServico;
    private javax.swing.JTable cadastroServico;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tableCadastro;
    private javax.swing.JPanel tabledColaborador;
    private javax.swing.JPanel tabledServico;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textPreco;
    // End of variables declaration//GEN-END:variables
}
