/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Connection.ConexaoBD;
import Controller.HashtableVeiculoController;
import Model.Cliente;
import Model.Veiculos;
import static Persistence.VeiculosDAO.selectVeiculos;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Enumeration;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guerra
 */
public class ConsultaVeiculos extends javax.swing.JFrame {

    private HashtableVeiculoController repositorio;

    public ConsultaVeiculos() {
        repositorio = new HashtableVeiculoController();
        initComponents();
        carregarVeiculosNaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cadastroCarro = new javax.swing.JScrollPane();
        cadastroVeiculos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        textBusca = new javax.swing.JTextField();
        buttonBuscar = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cadastroVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Marca", "Placa", "Chassi", "Patrimonio", "KM", "Acessorios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cadastroVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroVeiculosMouseClicked(evt);
            }
        });
        cadastroCarro.setViewportView(cadastroVeiculos);

        jLabel1.setText("Buscar Veiculos");

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonRefresh)
                            .addComponent(buttonBuscar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cadastroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(cadastroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void carregarVeiculosNaTabela() {
        try (Connection conexao = ConexaoBD.getConexao()) {
            if (conexao != null && !conexao.isClosed()) {
                repositorio.clear(); // Limpa o repositório antes de carregar os veículos

                // Chama o método selectVeiculos para carregar os dados
                selectVeiculos(conexao, repositorio);

                // Obtém o modelo da tabela e limpa as linhas
                DefaultTableModel model = (DefaultTableModel) cadastroVeiculos.getModel();
                model.setRowCount(0);

                // Preenche a tabela com os veículos do repositório
                Enumeration<Veiculos> veiculosEnum = repositorio.listarTodosVeiculos().elements();
                while (veiculosEnum.hasMoreElements()) {
                    Veiculos veiculo = veiculosEnum.nextElement();
                    model.addRow(new Object[]{
                        veiculo.getModelo(),
                        veiculo.getMarca(),
                        veiculo.getPlaca(),
                        veiculo.getChassi(),
                        veiculo.getPatrimonio(),
                        veiculo.getKilometragem(),
                        veiculo.getAcessorios()
                    });
                }
            }
        } catch (SQLException e) {
            System.err.println("Erro ao carregar os veículos: " + e.getMessage());
        } catch (Exception e) {
            System.err.println("Erro geral: " + e.getMessage());
        }
    }


    private void cadastroVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroVeiculosMouseClicked

    }//GEN-LAST:event_cadastroVeiculosMouseClicked

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        try (Connection conexao = ConexaoBD.getConexao()) {
            if (conexao != null && !conexao.isClosed()) {
                repositorio.clear(); // Limpa o repositório antes de carregar os veículos

                // Carrega todos os veículos na tabela
                selectVeiculos(conexao, repositorio);

                String placa = textBusca.getText().trim(); // Obtém a placa digitada no campo de busca
                Veiculos veiculoEncontrado = repositorio.buscarVeiculosPelaPlaca(placa);

                if (veiculoEncontrado != null) {
                    atualizarTabelaVeiculo(veiculoEncontrado); // Atualiza a tabela com o veículo encontrado
                } else {
                    System.out.println("Veículo não encontrado: " + placa);
                    limparTabela(); // Limpa a tabela caso o veículo não seja encontrado
                }
            }
        } catch (SQLException e) {
            System.err.println("Erro ao carregar os veículos: " + e.getMessage());
        } catch (Exception e) {
            System.err.println("Erro geral: " + e.getMessage());
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed
    private void limparTabela() {
    DefaultTableModel model = (DefaultTableModel) cadastroVeiculos.getModel();
    model.setRowCount(0);  // Limpa todas as linhas da tabela
}


private void atualizarTabelaVeiculo(Veiculos veiculo) {
    DefaultTableModel model = (DefaultTableModel) cadastroVeiculos.getModel();
    model.setRowCount(0);  // Limpa a tabela antes de adicionar o veículo encontrado

    // Adiciona o veículo encontrado na tabela
    model.addRow(new Object[]{
        veiculo.getModelo(),
        veiculo.getMarca(),
        veiculo.getPlaca(),
        veiculo.getChassi(),
        veiculo.getPatrimonio(),
        veiculo.getKilometragem(),
        veiculo.getAcessorios()
    });
}
    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
       carregarVeiculosNaTabela();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JScrollPane cadastroCarro;
    private javax.swing.JTable cadastroVeiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textBusca;
    // End of variables declaration//GEN-END:variables
}
