/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Connection.ConexaoBD;
import Persistence.ClientesDAO;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Guerra
 */
public class OrdemServicoview extends javax.swing.JFrame {

    private final ClientesDAO clientesDAO;

    /**
     * Creates new form OrdemServiço
     *
     * @throws java.lang.Exception
     */
    public OrdemServicoview() throws Exception {
        initComponents();
        configurarScrollPane();
        clientesDAO = new ClientesDAO(); // Inicializa o objeto ClientesDAO
        ListasNomes.setVisible(false);
        ScrollLista.setVisible(false);

    }

    private void configurarScrollPane() {
        JScrollPane scrollPane = new JScrollPane(ordemServico);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        panelScroll.setLayout(new BorderLayout());
        panelScroll.add(scrollPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScroll = new javax.swing.JPanel();
        ordemServico = new javax.swing.JPanel();
        panelCliente = new javax.swing.JPanel();
        ScrollLista = new javax.swing.JScrollPane();
        ListasNomes = new javax.swing.JList<>();
        textoCliente = new javax.swing.JTextField();
        labelCliente = new javax.swing.JLabel();
        buttonAdicionarCliente = new javax.swing.JButton();
        textcodOS = new javax.swing.JTextField();
        LabelCodigoOs = new javax.swing.JLabel();
        textIdentificador = new javax.swing.JTextField();
        labelIdentificador = new javax.swing.JLabel();
        labalEndereco = new javax.swing.JLabel();
        textEndereco = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        textTelefones = new javax.swing.JTextField();
        labelContato = new javax.swing.JLabel();
        textContato = new javax.swing.JTextField();
        labelInsEst = new javax.swing.JLabel();
        textInsEst = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        statusCombox = new javax.swing.JComboBox<>();
        panelVeiculos = new javax.swing.JPanel();
        veiculoclienteVinculado = new javax.swing.JTextField();
        labelVeiculos = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        textModelo = new javax.swing.JTextField();
        labelPlaca = new javax.swing.JLabel();
        textPlaca = new javax.swing.JTextField();
        labelMarca = new javax.swing.JLabel();
        textMarca = new javax.swing.JTextField();
        labelChassi = new javax.swing.JLabel();
        textChassi = new javax.swing.JTextField();
        labelKM = new javax.swing.JLabel();
        textKM = new javax.swing.JTextField();
        labelAcess = new javax.swing.JLabel();
        textAccs = new javax.swing.JTextField();
        panelNome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Servico = new javax.swing.JPanel();
        comboxServicos = new javax.swing.JComboBox<>();
        labelServico = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        textValor = new javax.swing.JTextField();
        adicionarServico = new javax.swing.JButton();
        removerServico = new javax.swing.JButton();
        comboxColaborador = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        adicionarColaborador = new javax.swing.JButton();
        Pecas = new javax.swing.JPanel();
        labelPecas = new javax.swing.JLabel();
        comboxPecas = new javax.swing.JComboBox<>();
        spinnerPecas = new javax.swing.JSpinner();
        adicionarPecas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePecassub = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableServicoexecutar = new javax.swing.JTable();
        painelFinal = new javax.swing.JPanel();
        labelPagamento = new javax.swing.JLabel();
        escolhaPagamento = new javax.swing.JComboBox<>();
        labelTotal = new javax.swing.JLabel();
        textValorTotal = new javax.swing.JTextField();
        novoOs = new javax.swing.JButton();
        salvarOs = new javax.swing.JButton();
        excluirOs = new javax.swing.JButton();
        pesquisarOs = new javax.swing.JButton();
        gerarOspdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        panelCliente.setLayout(null);

        ScrollLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ListasNomes.setBorder(null);
        ListasNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListasNomesMouseClicked(evt);
            }
        });
        ScrollLista.setViewportView(ListasNomes);

        panelCliente.add(ScrollLista);
        ScrollLista.setBounds(250, 50, 210, 100);

        textoCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClienteActionPerformed(evt);
            }
        });
        textoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textoClienteKeyReleased(evt);
            }
        });
        panelCliente.add(textoCliente);
        textoCliente.setBounds(250, 30, 211, 20);

        labelCliente.setText("Cliente");
        panelCliente.add(labelCliente);
        labelCliente.setBounds(251, 10, 98, 16);

        buttonAdicionarCliente.setText("Adicionar");
        buttonAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarClienteActionPerformed(evt);
            }
        });
        panelCliente.add(buttonAdicionarCliente);
        buttonAdicionarCliente.setBounds(540, 30, 81, 23);
        panelCliente.add(textcodOS);
        textcodOS.setBounds(34, 29, 87, 31);

        LabelCodigoOs.setText("Código OS");
        panelCliente.add(LabelCodigoOs);
        LabelCodigoOs.setBounds(34, 9, 58, 16);

        textIdentificador.setEditable(false);
        panelCliente.add(textIdentificador);
        textIdentificador.setBounds(726, 21, 199, 30);

        labelIdentificador.setText("CPF/CNPJ");
        panelCliente.add(labelIdentificador);
        labelIdentificador.setBounds(727, 7, 100, 16);

        labalEndereco.setText("Endereço");
        panelCliente.add(labalEndereco);
        labalEndereco.setBounds(726, 57, 61, 16);

        textEndereco.setEditable(false);
        panelCliente.add(textEndereco);
        textEndereco.setBounds(726, 71, 377, 30);

        labelEndereco.setText("Fones");
        panelCliente.add(labelEndereco);
        labelEndereco.setBounds(934, 7, 70, 16);

        textTelefones.setEditable(false);
        panelCliente.add(textTelefones);
        textTelefones.setBounds(937, 21, 237, 30);

        labelContato.setText("Contato");
        panelCliente.add(labelContato);
        labelContato.setBounds(1188, 7, 80, 16);
        panelCliente.add(textContato);
        textContato.setBounds(1192, 21, 186, 30);

        labelInsEst.setText("Ins.Est");
        panelCliente.add(labelInsEst);
        labelInsEst.setBounds(1115, 57, 70, 16);

        textInsEst.setEditable(false);
        panelCliente.add(textInsEst);
        textInsEst.setBounds(1115, 71, 253, 30);

        labelEmail.setText("E-mail");
        panelCliente.add(labelEmail);
        labelEmail.setBounds(726, 107, 59, 16);

        textEmail.setEditable(false);
        panelCliente.add(textEmail);
        textEmail.setBounds(726, 121, 377, 30);

        statusCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Aberta", "Em andamento", "Concluida", "Cancelada" }));
        statusCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboxActionPerformed(evt);
            }
        });
        panelCliente.add(statusCombox);
        statusCombox.setBounds(32, 90, 90, 22);

        panelVeiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        veiculoclienteVinculado.setEditable(false);

        labelVeiculos.setText("Veiculo");

        labelModelo.setText("Modelo");

        textModelo.setEditable(false);

        labelPlaca.setText("Placa");

        labelMarca.setText("Marca");

        labelChassi.setText("N Chassi");

        labelKM.setText("Kilometragem");

        labelAcess.setText("Acessorios");

        javax.swing.GroupLayout panelVeiculosLayout = new javax.swing.GroupLayout(panelVeiculos);
        panelVeiculos.setLayout(panelVeiculosLayout);
        panelVeiculosLayout.setHorizontalGroup(
            panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVeiculosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelVeiculos)
                    .addComponent(labelMarca)
                    .addComponent(textMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(veiculoclienteVinculado))
                .addGap(18, 18, 18)
                .addGroup(panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVeiculosLayout.createSequentialGroup()
                        .addComponent(textPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textKM, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelVeiculosLayout.createSequentialGroup()
                        .addGroup(panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelModelo)
                            .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPlaca))
                        .addGap(18, 18, 18)
                        .addGroup(panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelChassi)
                            .addGroup(panelVeiculosLayout.createSequentialGroup()
                                .addComponent(labelKM)
                                .addGap(161, 161, 161)
                                .addGroup(panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAcess)
                                    .addComponent(textAccs, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVeiculosLayout.setVerticalGroup(
            panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVeiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVeiculos)
                    .addComponent(labelModelo)
                    .addComponent(labelChassi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veiculoclienteVinculado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlaca)
                    .addComponent(labelMarca)
                    .addComponent(labelKM)
                    .addComponent(labelAcess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAccs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNome.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ordem de Serviço");

        javax.swing.GroupLayout panelNomeLayout = new javax.swing.GroupLayout(panelNome);
        panelNome.setLayout(panelNomeLayout);
        panelNomeLayout.setHorizontalGroup(
            panelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNomeLayout.createSequentialGroup()
                .addGap(721, 721, 721)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNomeLayout.setVerticalGroup(
            panelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNomeLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        Servico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        comboxServicos.setEditable(true);

        labelServico.setText("Serviços");

        labelValor.setText("Valor R$:");

        adicionarServico.setText("Adicionar");

        removerServico.setText("Remover");

        comboxColaborador.setEditable(true);
        comboxColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxColaboradorActionPerformed(evt);
            }
        });

        jLabel2.setText("Colaborador");

        adicionarColaborador.setText("Adicionar");

        javax.swing.GroupLayout ServicoLayout = new javax.swing.GroupLayout(Servico);
        Servico.setLayout(ServicoLayout);
        ServicoLayout.setHorizontalGroup(
            ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ServicoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ServicoLayout.createSequentialGroup()
                        .addGroup(ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboxColaborador, 0, 308, Short.MAX_VALUE)
                            .addComponent(labelServico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboxServicos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValor)
                            .addGroup(ServicoLayout.createSequentialGroup()
                                .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(adicionarServico)
                                .addGap(18, 18, 18)
                                .addComponent(removerServico))
                            .addComponent(adicionarColaborador))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ServicoLayout.setVerticalGroup(
            ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServico)
                    .addComponent(labelValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarServico)
                    .addComponent(removerServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarColaborador))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Pecas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        labelPecas.setText("Peças");

        comboxPecas.setEditable(true);

        adicionarPecas.setText("Adicionar");

        javax.swing.GroupLayout PecasLayout = new javax.swing.GroupLayout(Pecas);
        Pecas.setLayout(PecasLayout);
        PecasLayout.setHorizontalGroup(
            PecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PecasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPecas)
                    .addGroup(PecasLayout.createSequentialGroup()
                        .addComponent(comboxPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adicionarPecas)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        PecasLayout.setVerticalGroup(
            PecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PecasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPecas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarPecas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePecassub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Peças a substituir", "Qtd", "Valor Un", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablePecassub);
        if (tablePecassub.getColumnModel().getColumnCount() > 0) {
            tablePecassub.getColumnModel().getColumn(0).setMinWidth(100);
            tablePecassub.getColumnModel().getColumn(0).setPreferredWidth(400);
            tablePecassub.getColumnModel().getColumn(0).setMaxWidth(350);
        }

        tableServicoexecutar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Serviços a Executar"
            }
        ));
        jScrollPane2.setViewportView(tableServicoexecutar);

        painelFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        labelPagamento.setText("Forma de Pagar");

        escolhaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão de Crédito", "Cartão de Débito", "PIX", "Dinheiro" }));

        labelTotal.setText("TOTAL R$:");

        javax.swing.GroupLayout painelFinalLayout = new javax.swing.GroupLayout(painelFinal);
        painelFinal.setLayout(painelFinalLayout);
        painelFinalLayout.setHorizontalGroup(
            painelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFinalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(painelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(painelFinalLayout.createSequentialGroup()
                        .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelFinalLayout.createSequentialGroup()
                        .addComponent(textValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(escolhaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelFinalLayout.setVerticalGroup(
            painelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFinalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(painelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPagamento)
                    .addComponent(labelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escolhaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        novoOs.setText("Novo");

        salvarOs.setText("Salvar");

        excluirOs.setText("Excluir");

        pesquisarOs.setText("Pesquisar");

        gerarOspdf.setText("Gerar");

        javax.swing.GroupLayout ordemServicoLayout = new javax.swing.GroupLayout(ordemServico);
        ordemServico.setLayout(ordemServicoLayout);
        ordemServicoLayout.setHorizontalGroup(
            ordemServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ordemServicoLayout.createSequentialGroup()
                .addGroup(ordemServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ordemServicoLayout.createSequentialGroup()
                        .addComponent(Servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(ordemServicoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(novoOs)
                        .addGap(18, 18, 18)
                        .addComponent(salvarOs)
                        .addGap(18, 18, 18)
                        .addComponent(excluirOs)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisarOs)
                        .addGap(18, 18, 18)
                        .addComponent(gerarOspdf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 473, Short.MAX_VALUE))
                    .addGroup(ordemServicoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(ordemServicoLayout.createSequentialGroup()
                        .addComponent(painelFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)))
                .addGroup(ordemServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(Pecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ordemServicoLayout.setVerticalGroup(
            ordemServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordemServicoLayout.createSequentialGroup()
                .addComponent(panelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ordemServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ordemServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ordemServicoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(ordemServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(novoOs)
                            .addComponent(salvarOs)
                            .addComponent(excluirOs)
                            .addComponent(pesquisarOs)
                            .addComponent(gerarOspdf)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelScrollLayout = new javax.swing.GroupLayout(panelScroll);
        panelScroll.setLayout(panelScrollLayout);
        panelScrollLayout.setHorizontalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordemServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelScrollLayout.setVerticalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelScrollLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ordemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboxColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxColaboradorActionPerformed
    }//GEN-LAST:event_comboxColaboradorActionPerformed

    private void buttonAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdicionarClienteActionPerformed

    private void textoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClienteActionPerformed

    private void statusComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboxActionPerformed

    private void textoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoClienteKeyReleased
        ListarNomes();
    }//GEN-LAST:event_textoClienteKeyReleased

    private void ListasNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListasNomesMouseClicked
        buscarNome();
    }//GEN-LAST:event_ListasNomesMouseClicked
    private void ListarNomes() {
        DefaultListModel<String> model = new DefaultListModel<>();
        ListasNomes.setModel(model);

        // Consulta SQL corrigida
        String readLista = "SELECT nome FROM clientes WHERE nome LIKE ? ORDER BY nome";
        try {
            // Estabelecendo a conexão com o banco de dados
            Connection conexao = ConexaoBD.getConexao();

            PreparedStatement preparedStatement = conexao.prepareStatement(readLista);

            preparedStatement.setString(1, textoCliente.getText() + "%");

            // Executando a consulta
            ResultSet rs = preparedStatement.executeQuery();

            model.clear();

            while (rs.next()) {
                ScrollLista.setVisible(true);
                ListasNomes.setVisible(true);
                model.addElement(rs.getString("nome"));
            }

            rs.close();
            preparedStatement.close();
        } catch (Exception e) {
            System.out.println(e);  // Imprimindo o erro, se ocorrer
        }
    }

    private void buscarNome() {
        // Obter o índice da linha selecionada
        int linha = ListasNomes.getSelectedIndex();

        if (linha >= 0) {
            // Construção da consulta SQL para buscar os dados principais do cliente
            String sqlCliente = "SELECT c.id AS id_cliente, c.nome, c.email, c.logradouro, c.telefone, "
                    + "pf.cpf, pj.cnpj, pj.contato, pj.insc_estadual "
                    + "FROM clientes c "
                    + "LEFT JOIN pessoa_fisica pf ON c.id = pf.id_cliente "
                    + "LEFT JOIN pessoa_juridica pj ON c.id = pj.id_cliente "
                    + "WHERE c.nome LIKE ? ORDER BY c.nome LIMIT 1 OFFSET ?";

            try {
                // Estabelecendo a conexão com o banco de dados
                Connection conexao = ConexaoBD.getConexao();

                // Preparando a consulta com os parâmetros
                PreparedStatement preparedStatement = conexao.prepareStatement(sqlCliente);
                preparedStatement.setString(1, textoCliente.getText() + "%"); // Nome com wildcard
                preparedStatement.setInt(2, linha); // Offset baseado na linha selecionada

                // Executando a consulta e obtendo o resultado
                ResultSet rs = preparedStatement.executeQuery();

                // Verifica se o cliente foi encontrado
                if (rs.next()) {
                    // Atualiza os campos básicos do cliente
                    ScrollLista.setVisible(false);
                    textoCliente.setText(rs.getString("nome"));
                    textEmail.setText(rs.getString("email"));
                    textEndereco.setText(rs.getString("logradouro"));
                    textTelefones.setText(rs.getString("telefone"));

                    // Preenche o campo identificador com CPF ou CNPJ (ou ambos)
                    String cpf = rs.getString("cpf");
                    String cnpj = rs.getString("cnpj");

                    // Caso tenha CPF e CNPJ, exibe ambos no mesmo campo
                    if (cpf != null) {
                        // Caso tenha apenas CPF
                        textIdentificador.setText(cpf);
                    } else if (cnpj != null) {
                        // Caso tenha apenas CNPJ
                        textIdentificador.setText(cnpj);
                    } else {
                        // Caso nenhum esteja presente
                        textIdentificador.setText("Não informado");
                    }

                    // Preenche os outros campos relacionados a Pessoa Jurídica, caso exista
                    textContato.setText(rs.getString("contato") != null ? rs.getString("contato") : "");
                    textInsEst.setText(rs.getString("insc_estadual") != null ? rs.getString("insc_estadual") : "");

                } else {
                    JOptionPane.showMessageDialog(null, "Cliente não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                }

                // Fechar recursos
                rs.close();
                preparedStatement.close();

            } catch (Exception e) {
                // Exibe erro no console para depuração
                System.out.println("Erro ao realizar a busca: " + e);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemServicoview.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemServicoview.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemServicoview.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemServicoview.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OrdemServicoview().setVisible(true);

                } catch (Exception ex) {
                    Logger.getLogger(OrdemServicoview.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCodigoOs;
    private javax.swing.JList<String> ListasNomes;
    private javax.swing.JPanel Pecas;
    private javax.swing.JScrollPane ScrollLista;
    private javax.swing.JPanel Servico;
    private javax.swing.JButton adicionarColaborador;
    private javax.swing.JButton adicionarPecas;
    private javax.swing.JButton adicionarServico;
    private javax.swing.JButton buttonAdicionarCliente;
    private javax.swing.JComboBox<String> comboxColaborador;
    private javax.swing.JComboBox<String> comboxPecas;
    private javax.swing.JComboBox<String> comboxServicos;
    private javax.swing.JComboBox<String> escolhaPagamento;
    private javax.swing.JButton excluirOs;
    private javax.swing.JButton gerarOspdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labalEndereco;
    private javax.swing.JLabel labelAcess;
    private javax.swing.JLabel labelChassi;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelContato;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelIdentificador;
    private javax.swing.JLabel labelInsEst;
    private javax.swing.JLabel labelKM;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelPagamento;
    private javax.swing.JLabel labelPecas;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelServico;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelVeiculos;
    private javax.swing.JButton novoOs;
    private javax.swing.JPanel ordemServico;
    private javax.swing.JPanel painelFinal;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelNome;
    private javax.swing.JPanel panelScroll;
    private javax.swing.JPanel panelVeiculos;
    private javax.swing.JButton pesquisarOs;
    private javax.swing.JButton removerServico;
    private javax.swing.JButton salvarOs;
    private javax.swing.JSpinner spinnerPecas;
    private javax.swing.JComboBox<String> statusCombox;
    private javax.swing.JTable tablePecassub;
    private javax.swing.JTable tableServicoexecutar;
    private javax.swing.JTextField textAccs;
    private javax.swing.JTextField textChassi;
    private javax.swing.JTextField textContato;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textIdentificador;
    private javax.swing.JTextField textInsEst;
    private javax.swing.JTextField textKM;
    private javax.swing.JTextField textMarca;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textPlaca;
    private javax.swing.JTextField textTelefones;
    private javax.swing.JTextField textValor;
    private javax.swing.JTextField textValorTotal;
    private javax.swing.JTextField textcodOS;
    private javax.swing.JTextField textoCliente;
    private javax.swing.JTextField veiculoclienteVinculado;
    // End of variables declaration//GEN-END:variables
}
